# Generated by Django 4.2.7 on 2025-11-11 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=50, unique=True, verbose_name='환자 ID')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('birth_date', models.DateField(verbose_name='생년월일')),
                ('gender', models.CharField(choices=[('M', '남성'), ('F', '여성')], max_length=1, verbose_name='성별')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='전화번호')),
                ('address', models.TextField(blank=True, verbose_name='주소')),
                ('emergency_contact', models.CharField(blank=True, max_length=100, verbose_name='비상연락처')),
                ('medical_history', models.TextField(blank=True, verbose_name='과거 병력')),
                ('allergies', models.TextField(blank=True, verbose_name='알레르기')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '환자',
                'verbose_name_plural': '환자들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(verbose_name='방문일시')),
                ('diagnosis', models.CharField(max_length=200, verbose_name='진단')),
                ('symptoms', models.TextField(verbose_name='증상')),
                ('treatment', models.TextField(verbose_name='치료내용')),
                ('prescription', models.TextField(blank=True, verbose_name='처방전')),
                ('doctor_notes', models.TextField(blank=True, verbose_name='의사 소견')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='patients.patient', verbose_name='환자')),
            ],
        ),
    ]
