# Generated by Django 4.2.7 on 2025-11-11 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = []
