# Generated by Django 4.2.7 on 2025-11-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_add_patient_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={'ordering': ['-visit_date'], 'verbose_name': '진료 기록', 'verbose_name_plural': '진료 기록들'},
        ),
        migrations.AddField(
            model_name='patientuser',
            name='account_id',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='계정 ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='생년월일'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '남성'), ('F', '여성')], max_length=1, null=True, verbose_name='성별'),
        ),
    ]
