# Generated by Django 4.2.7 on 2025-11-11 12:41

from django.db import migrations, models
import django.db.models.deletion


def cleanup_patient_user(apps, schema_editor):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        # Drop existing FK from patients_patient to patient_user if present
        cursor.execute(
            """
            SELECT CONSTRAINT_NAME
            FROM information_schema.KEY_COLUMN_USAGE
            WHERE TABLE_SCHEMA = DATABASE()
              AND TABLE_NAME = 'patients_patient'
              AND REFERENCED_TABLE_NAME = 'patient_user'
            LIMIT 1
            """
        )
        row = cursor.fetchone()
        if row and row[0]:
            cursor.execute(
                f"ALTER TABLE patients_patient DROP FOREIGN KEY {row[0]}"
            )

        # Drop column if it already exists
        cursor.execute(
            """
            SELECT COUNT(*)
            FROM information_schema.COLUMNS
            WHERE TABLE_SCHEMA = DATABASE()
              AND TABLE_NAME = 'patients_patient'
              AND COLUMN_NAME = 'user_account_id'
            """
        )
        if cursor.fetchone()[0]:
            cursor.execute("ALTER TABLE patients_patient DROP COLUMN user_account_id")

        # Drop junction tables referencing patient_user (auth relations)
        for table_name in [
            "patient_user_groups",
            "patient_user_user_permissions",
        ]:
            cursor.execute(
                """
                SELECT COUNT(*)
                FROM information_schema.TABLES
                WHERE TABLE_SCHEMA = DATABASE()
                  AND TABLE_NAME = %s
                """,
                (table_name,),
            )
            if cursor.fetchone()[0]:
                cursor.execute(f"DROP TABLE {table_name}")

        # Drop legacy patient_user table if it exists
        cursor.execute(
            """
            SELECT COUNT(*)
            FROM information_schema.TABLES
            WHERE TABLE_SCHEMA = DATABASE()
              AND TABLE_NAME = 'patient_user'
            """
        )
        if cursor.fetchone()[0]:
            cursor.execute("DROP TABLE patient_user")


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('patients', '0004_delete_appointment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={'ordering': ['-visit_date'], 'verbose_name': '진료 기록', 'verbose_name_plural': '진료 기록들'},
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='생년월일'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '남성'), ('F', '여성')], max_length=1, null=True, verbose_name='성별'),
        ),
        migrations.RunPython(cleanup_patient_user, migrations.RunPython.noop),
        migrations.CreateModel(
            name='PatientUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('account_id', models.CharField(max_length=50, unique=True, verbose_name='계정 ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('patient_id', models.CharField(max_length=50, unique=True, verbose_name='환자 ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='전화번호')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
                ('is_staff', models.BooleanField(default=False, verbose_name='스태프 여부')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
                ('groups', models.ManyToManyField(blank=True, related_name='patient_users', to='auth.group', verbose_name='소속 그룹')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='patient_users', to='auth.permission', verbose_name='개별 권한')),
            ],
            options={
                'verbose_name': '환자 계정',
                'verbose_name_plural': '환자 계정',
                'db_table': 'patient_user',
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='user_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_profile', to='patients.patientuser', verbose_name='연결된 환자 계정'),
        ),
    ]
