# Generated by Django 4.2.7 on 2025-11-11 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('patients', '0004_delete_appointment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={'ordering': ['-visit_date'], 'verbose_name': '진료 기록', 'verbose_name_plural': '진료 기록들'},
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='생년월일'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '남성'), ('F', '여성')], max_length=1, null=True, verbose_name='성별'),
        ),
        migrations.CreateModel(
            name='PatientUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('account_id', models.CharField(max_length=50, unique=True, verbose_name='계정 ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('patient_id', models.CharField(max_length=50, unique=True, verbose_name='환자 ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='전화번호')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
                ('is_staff', models.BooleanField(default=False, verbose_name='스태프 여부')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
                ('groups', models.ManyToManyField(blank=True, related_name='patient_users', to='auth.group', verbose_name='소속 그룹')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='patient_users', to='auth.permission', verbose_name='개별 권한')),
            ],
            options={
                'verbose_name': '환자 계정',
                'verbose_name_plural': '환자 계정',
                'db_table': 'patient_user',
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='user_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_profile', to='patients.patientuser', verbose_name='연결된 환자 계정'),
        ),
    ]
