# Generated by Django 4.2.7 on 2025-10-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LungCancerSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.IntegerField(choices=[(1, '남성'), (0, '여성')], verbose_name='성별')),
                ('age', models.IntegerField(verbose_name='나이')),
                ('smoking', models.IntegerField(choices=[(2, '예'), (1, '아니오')], verbose_name='흡연')),
                ('yellow_fingers', models.IntegerField(choices=[(2, '예'), (1, '아니오')], verbose_name='손가락 변색')),
                ('anxiety', models.IntegerField(choices=[(2, '예'), (1, '아니오')], verbose_name='불안')),
                ('peer_pressure', models.IntegerField(choices=[(2, '예'), (1, '아니오')], verbose_name='또래 압박')),
                ('chronic_disease', models.IntegerField(choices=[(2, '예'), (1, '아니오')], verbose_name='만성 질환')),
                ('fatigue', models.IntegerField(choices=[(2, '예'), (1, '아니오')], verbose_name='피로')),
                ('allergy', models.IntegerField(choices=[(2, '예'), (1, '아니오')], verbose_name='알레르기')),
                ('wheezing', models.IntegerField(choices=[(2, '예'), (1, '아니오')], verbose_name='쌕쌕거림')),
                ('alcohol_consuming', models.IntegerField(choices=[(2, '예'), (1, '아니오')], verbose_name='음주')),
                ('coughing', models.IntegerField(choices=[(2, '예'), (1, '아니오')], verbose_name='기침')),
                ('shortness_of_breath', models.IntegerField(choices=[(2, '예'), (1, '아니오')], verbose_name='호흡 곤란')),
                ('swallowing_difficulty', models.IntegerField(choices=[(2, '예'), (1, '아니오')], verbose_name='삼킴 곤란')),
                ('chest_pain', models.IntegerField(choices=[(2, '예'), (1, '아니오')], verbose_name='가슴 통증')),
                ('lung_cancer', models.IntegerField(choices=[(2, '예'), (1, '아니오')], verbose_name='폐암 진단')),
            ],
            options={
                'verbose_name': '폐암 설문조사',
                'verbose_name_plural': '폐암 설문조사 목록',
                'db_table': 'lung_cancer_survey',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LungRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10, verbose_name='성별')),
                ('age', models.IntegerField(verbose_name='나이')),
                ('smoking', models.IntegerField(choices=[(2, '예'), (1, '아니오')], verbose_name='흡연')),
                ('yellow_fingers', models.IntegerField(choices=[(2, '예'), (1, '아니오')], verbose_name='손가락 변색')),
                ('anxiety', models.IntegerField(choices=[(2, '예'), (1, '아니오')], verbose_name='불안')),
                ('peer_pressure', models.IntegerField(choices=[(2, '예'), (1, '아니오')], verbose_name='또래 압박')),
                ('chronic_disease', models.IntegerField(choices=[(2, '예'), (1, '아니오')], verbose_name='만성 질환')),
                ('fatigue', models.IntegerField(choices=[(2, '예'), (1, '아니오')], verbose_name='피로')),
                ('allergy', models.IntegerField(choices=[(2, '예'), (1, '아니오')], verbose_name='알레르기')),
                ('wheezing', models.IntegerField(choices=[(2, '예'), (1, '아니오')], verbose_name='쌕쌕거림')),
                ('alcohol_consuming', models.IntegerField(choices=[(2, '예'), (1, '아니오')], verbose_name='음주')),
                ('coughing', models.IntegerField(choices=[(2, '예'), (1, '아니오')], verbose_name='기침')),
                ('shortness_of_breath', models.IntegerField(choices=[(2, '예'), (1, '아니오')], verbose_name='호흡 곤란')),
                ('swallowing_difficulty', models.IntegerField(choices=[(2, '예'), (1, '아니오')], verbose_name='삼킴 곤란')),
                ('chest_pain', models.IntegerField(choices=[(2, '예'), (1, '아니오')], verbose_name='가슴 통증')),
                ('lung_cancer', models.IntegerField(choices=[(2, '예'), (1, '아니오')], verbose_name='폐암')),
            ],
            options={
                'verbose_name': '폐암 검사 기록',
                'verbose_name_plural': '폐암 검사 기록 목록',
                'db_table': 'lung_record',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LungResult',
            fields=[
                ('result_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('record_id', models.IntegerField(verbose_name='기록 ID')),
                ('name', models.CharField(max_length=100, verbose_name='환자명')),
                ('gender', models.CharField(max_length=10, verbose_name='성별')),
                ('age', models.IntegerField(verbose_name='나이')),
                ('prediction', models.CharField(max_length=10, verbose_name='예측 결과')),
                ('risk_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='위험 점수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
            options={
                'verbose_name': '폐암 검사 결과',
                'verbose_name_plural': '폐암 검사 결과 목록',
                'db_table': 'lung_result',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='환자명')),
                ('gender', models.IntegerField(choices=[(1, '남성'), (0, '여성')], verbose_name='성별')),
                ('age', models.IntegerField(verbose_name='나이')),
                ('smoking', models.IntegerField(choices=[(2, '예'), (1, '아니오')], verbose_name='흡연')),
                ('yellow_fingers', models.IntegerField(choices=[(2, '예'), (1, '아니오')], verbose_name='손가락 변색')),
                ('anxiety', models.IntegerField(choices=[(2, '예'), (1, '아니오')], verbose_name='불안')),
                ('peer_pressure', models.IntegerField(choices=[(2, '예'), (1, '아니오')], verbose_name='또래 압박')),
                ('chronic_disease', models.IntegerField(choices=[(2, '예'), (1, '아니오')], verbose_name='만성 질환')),
                ('fatigue', models.IntegerField(choices=[(2, '예'), (1, '아니오')], verbose_name='피로')),
                ('allergy', models.IntegerField(choices=[(2, '예'), (1, '아니오')], verbose_name='알레르기')),
                ('wheezing', models.IntegerField(choices=[(2, '예'), (1, '아니오')], verbose_name='쌕쌕거림')),
                ('alcohol_consuming', models.IntegerField(choices=[(2, '예'), (1, '아니오')], verbose_name='음주')),
                ('coughing', models.IntegerField(choices=[(2, '예'), (1, '아니오')], verbose_name='기침')),
                ('shortness_of_breath', models.IntegerField(choices=[(2, '예'), (1, '아니오')], verbose_name='호흡 곤란')),
                ('swallowing_difficulty', models.IntegerField(choices=[(2, '예'), (1, '아니오')], verbose_name='삼킴 곤란')),
                ('chest_pain', models.IntegerField(choices=[(2, '예'), (1, '아니오')], verbose_name='가슴 통증')),
                ('prediction', models.CharField(blank=True, max_length=10, null=True, verbose_name='예측 결과')),
                ('prediction_probability', models.FloatField(blank=True, null=True, verbose_name='예측 확률')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '환자',
                'verbose_name_plural': '환자 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
