# Generated by Django 4.2.7 on 2025-10-29 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lung_cancer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='환자id')),
                ('name', models.CharField(max_length=100, verbose_name='환자명')),
                ('birth_date', models.DateField(verbose_name='생년월일')),
                ('gender', models.CharField(max_length=10, verbose_name='성별')),
                ('phone', models.CharField(max_length=20, verbose_name='전화번호')),
                ('address', models.TextField(verbose_name='주소')),
                ('emergency_contact', models.CharField(max_length=20, verbose_name='응급연락처')),
                ('blood_type', models.CharField(max_length=5, verbose_name='혈액형')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '환자',
                'verbose_name_plural': '환자 목록',
                'db_table': 'patient',
                'managed': True,
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LungRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10, verbose_name='성별')),
                ('age', models.IntegerField(verbose_name='나이')),
                ('smoking', models.BooleanField(verbose_name='흡연')),
                ('yellow_fingers', models.BooleanField(verbose_name='손가락 변색')),
                ('anxiety', models.BooleanField(verbose_name='불안')),
                ('peer_pressure', models.BooleanField(verbose_name='또래 압박')),
                ('chronic_disease', models.BooleanField(verbose_name='만성 질환')),
                ('fatigue', models.BooleanField(verbose_name='피로')),
                ('allergy', models.BooleanField(verbose_name='알레르기')),
                ('wheezing', models.BooleanField(verbose_name='쌕쌕거림')),
                ('alcohol_consuming', models.BooleanField(verbose_name='음주')),
                ('coughing', models.BooleanField(verbose_name='기침')),
                ('shortness_of_breath', models.BooleanField(verbose_name='호흡 곤란')),
                ('swallowing_difficulty', models.BooleanField(verbose_name='삼킴 곤란')),
                ('chest_pain', models.BooleanField(verbose_name='가슴 통증')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lung_records', to='lung_cancer.patient')),
            ],
            options={
                'verbose_name': '폐암 검사 데이터',
                'verbose_name_plural': '폐암 검사 데이터 목록',
                'db_table': 'lung_record',
                'managed': True,
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LungResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.CharField(max_length=10, verbose_name='예측 결과')),
                ('risk_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='위험 점수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='검사일')),
                ('lung_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='lung_cancer.lungrecord')),
            ],
            options={
                'verbose_name': '폐암 검사 결과',
                'verbose_name_plural': '폐암 검사 결과 목록',
                'db_table': 'lung_result',
                'managed': True,
                'ordering': ['-created_at'],
            },
        ),
    ]