# Generated by Django 4.2.7 on 2025-10-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lung_cancer', '0002_auto_20251029_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=0, verbose_name='나이'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='smoking',
            field=models.BooleanField(default=False, verbose_name='흡연'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='yellow_fingers',
            field=models.BooleanField(default=False, verbose_name='손가락 변색'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='anxiety',
            field=models.BooleanField(default=False, verbose_name='불안'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='peer_pressure',
            field=models.BooleanField(default=False, verbose_name='또래 압박'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='chronic_disease',
            field=models.BooleanField(default=False, verbose_name='만성 질환'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='fatigue',
            field=models.BooleanField(default=False, verbose_name='피로'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='allergy',
            field=models.BooleanField(default=False, verbose_name='알레르기'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='wheezing',
            field=models.BooleanField(default=False, verbose_name='쌕쌕거림'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='alcohol_consuming',
            field=models.BooleanField(default=False, verbose_name='음주'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='coughing',
            field=models.BooleanField(default=False, verbose_name='기침'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='shortness_of_breath',
            field=models.BooleanField(default=False, verbose_name='호흡 곤란'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='swallowing_difficulty',
            field=models.BooleanField(default=False, verbose_name='삼킴 곤란'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='chest_pain',
            field=models.BooleanField(default=False, verbose_name='가슴 통증'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='prediction',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='예측 결과'),
        ),
        migrations.AddField(
            model_name='patient',
            name='prediction_probability',
            field=models.FloatField(blank=True, null=True, verbose_name='예측 확률'),
        ),
    ]