# Generated by Django 4.2.7 on 2025-10-29 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lung_cancer', '0003_auto_20251029_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='LungCancerPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smoking', models.BooleanField(default=False, verbose_name='흡연')),
                ('yellow_fingers', models.BooleanField(default=False, verbose_name='손가락 변색')),
                ('anxiety', models.BooleanField(default=False, verbose_name='불안')),
                ('peer_pressure', models.BooleanField(default=False, verbose_name='또래 압박')),
                ('chronic_disease', models.BooleanField(default=False, verbose_name='만성 질환')),
                ('fatigue', models.BooleanField(default=False, verbose_name='피로')),
                ('allergy', models.BooleanField(default=False, verbose_name='알레르기')),
                ('wheezing', models.BooleanField(default=False, verbose_name='쌕쌕거림')),
                ('alcohol_consuming', models.BooleanField(default=False, verbose_name='음주')),
                ('coughing', models.BooleanField(default=False, verbose_name='기침')),
                ('shortness_of_breath', models.BooleanField(default=False, verbose_name='호흡 곤란')),
                ('swallowing_difficulty', models.BooleanField(default=False, verbose_name='삼킴 곤란')),
                ('chest_pain', models.BooleanField(default=False, verbose_name='가슴 통증')),
                ('prediction', models.CharField(blank=True, max_length=10, null=True, verbose_name='예측 결과')),
                ('prediction_probability', models.FloatField(blank=True, null=True, verbose_name='예측 확률')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '폐암 환자',
                'verbose_name_plural': '폐암 환자 목록',
                'db_table': 'lung_cancer_patient',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='LungCancerSurvey',
        ),
        migrations.AlterModelOptions(
            name='lungrecord',
            options={'managed': False, 'ordering': ['-created_at'], 'verbose_name': '폐암 검사 데이터', 'verbose_name_plural': '폐암 검사 데이터 목록'},
        ),
        migrations.AlterModelOptions(
            name='lungresult',
            options={'managed': False, 'ordering': ['-created_at'], 'verbose_name': '폐암 검사 결과', 'verbose_name_plural': '폐암 검사 결과 목록'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'managed': False, 'ordering': ['-created_at'], 'verbose_name': '환자', 'verbose_name_plural': '환자 목록'},
        ),
    ]
