# Generated by Django 4.2.7 on 2025-10-29 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lung_cancer', '0004_lungcancerpatient_delete_lungcancersurvey_and_more'),
    ]

    operations = [
        # patient 테이블에서 폐암 관련 컬럼들 삭제 (MySQL 호환)
        migrations.RunSQL(
            """
            SET @sql = (SELECT IF(
                (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
                 WHERE table_name = 'patient' 
                 AND table_schema = DATABASE() 
                 AND column_name = 'smoking') > 0,
                'ALTER TABLE patient DROP COLUMN smoking',
                'SELECT 1'
            ));
            PREPARE stmt FROM @sql;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql="ALTER TABLE patient ADD COLUMN smoking BOOLEAN DEFAULT FALSE;"
        ),
        migrations.RunSQL(
            """
            SET @sql = (SELECT IF(
                (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
                 WHERE table_name = 'patient' 
                 AND table_schema = DATABASE() 
                 AND column_name = 'yellow_fingers') > 0,
                'ALTER TABLE patient DROP COLUMN yellow_fingers',
                'SELECT 1'
            ));
            PREPARE stmt FROM @sql;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql="ALTER TABLE patient ADD COLUMN yellow_fingers BOOLEAN DEFAULT FALSE;"
        ),
        migrations.RunSQL(
            """
            SET @sql = (SELECT IF(
                (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
                 WHERE table_name = 'patient' 
                 AND table_schema = DATABASE() 
                 AND column_name = 'anxiety') > 0,
                'ALTER TABLE patient DROP COLUMN anxiety',
                'SELECT 1'
            ));
            PREPARE stmt FROM @sql;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql="ALTER TABLE patient ADD COLUMN anxiety BOOLEAN DEFAULT FALSE;"
        ),
        migrations.RunSQL(
            """
            SET @sql = (SELECT IF(
                (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
                 WHERE table_name = 'patient' 
                 AND table_schema = DATABASE() 
                 AND column_name = 'peer_pressure') > 0,
                'ALTER TABLE patient DROP COLUMN peer_pressure',
                'SELECT 1'
            ));
            PREPARE stmt FROM @sql;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql="ALTER TABLE patient ADD COLUMN peer_pressure BOOLEAN DEFAULT FALSE;"
        ),
        migrations.RunSQL(
            """
            SET @sql = (SELECT IF(
                (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
                 WHERE table_name = 'patient' 
                 AND table_schema = DATABASE() 
                 AND column_name = 'chronic_disease') > 0,
                'ALTER TABLE patient DROP COLUMN chronic_disease',
                'SELECT 1'
            ));
            PREPARE stmt FROM @sql;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql="ALTER TABLE patient ADD COLUMN chronic_disease BOOLEAN DEFAULT FALSE;"
        ),
        migrations.RunSQL(
            """
            SET @sql = (SELECT IF(
                (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
                 WHERE table_name = 'patient' 
                 AND table_schema = DATABASE() 
                 AND column_name = 'fatigue') > 0,
                'ALTER TABLE patient DROP COLUMN fatigue',
                'SELECT 1'
            ));
            PREPARE stmt FROM @sql;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql="ALTER TABLE patient ADD COLUMN fatigue BOOLEAN DEFAULT FALSE;"
        ),
        migrations.RunSQL(
            """
            SET @sql = (SELECT IF(
                (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
                 WHERE table_name = 'patient' 
                 AND table_schema = DATABASE() 
                 AND column_name = 'allergy') > 0,
                'ALTER TABLE patient DROP COLUMN allergy',
                'SELECT 1'
            ));
            PREPARE stmt FROM @sql;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql="ALTER TABLE patient ADD COLUMN allergy BOOLEAN DEFAULT FALSE;"
        ),
        migrations.RunSQL(
            """
            SET @sql = (SELECT IF(
                (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
                 WHERE table_name = 'patient' 
                 AND table_schema = DATABASE() 
                 AND column_name = 'wheezing') > 0,
                'ALTER TABLE patient DROP COLUMN wheezing',
                'SELECT 1'
            ));
            PREPARE stmt FROM @sql;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql="ALTER TABLE patient ADD COLUMN wheezing BOOLEAN DEFAULT FALSE;"
        ),
        migrations.RunSQL(
            """
            SET @sql = (SELECT IF(
                (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
                 WHERE table_name = 'patient' 
                 AND table_schema = DATABASE() 
                 AND column_name = 'alcohol_consuming') > 0,
                'ALTER TABLE patient DROP COLUMN alcohol_consuming',
                'SELECT 1'
            ));
            PREPARE stmt FROM @sql;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql="ALTER TABLE patient ADD COLUMN alcohol_consuming BOOLEAN DEFAULT FALSE;"
        ),
        migrations.RunSQL(
            """
            SET @sql = (SELECT IF(
                (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
                 WHERE table_name = 'patient' 
                 AND table_schema = DATABASE() 
                 AND column_name = 'coughing') > 0,
                'ALTER TABLE patient DROP COLUMN coughing',
                'SELECT 1'
            ));
            PREPARE stmt FROM @sql;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql="ALTER TABLE patient ADD COLUMN coughing BOOLEAN DEFAULT FALSE;"
        ),
        migrations.RunSQL(
            """
            SET @sql = (SELECT IF(
                (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
                 WHERE table_name = 'patient' 
                 AND table_schema = DATABASE() 
                 AND column_name = 'shortness_of_breath') > 0,
                'ALTER TABLE patient DROP COLUMN shortness_of_breath',
                'SELECT 1'
            ));
            PREPARE stmt FROM @sql;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql="ALTER TABLE patient ADD COLUMN shortness_of_breath BOOLEAN DEFAULT FALSE;"
        ),
        migrations.RunSQL(
            """
            SET @sql = (SELECT IF(
                (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
                 WHERE table_name = 'patient' 
                 AND table_schema = DATABASE() 
                 AND column_name = 'swallowing_difficulty') > 0,
                'ALTER TABLE patient DROP COLUMN swallowing_difficulty',
                'SELECT 1'
            ));
            PREPARE stmt FROM @sql;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql="ALTER TABLE patient ADD COLUMN swallowing_difficulty BOOLEAN DEFAULT FALSE;"
        ),
        migrations.RunSQL(
            """
            SET @sql = (SELECT IF(
                (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
                 WHERE table_name = 'patient' 
                 AND table_schema = DATABASE() 
                 AND column_name = 'chest_pain') > 0,
                'ALTER TABLE patient DROP COLUMN chest_pain',
                'SELECT 1'
            ));
            PREPARE stmt FROM @sql;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql="ALTER TABLE patient ADD COLUMN chest_pain BOOLEAN DEFAULT FALSE;"
        ),
        migrations.RunSQL(
            """
            SET @sql = (SELECT IF(
                (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
                 WHERE table_name = 'patient' 
                 AND table_schema = DATABASE() 
                 AND column_name = 'prediction') > 0,
                'ALTER TABLE patient DROP COLUMN prediction',
                'SELECT 1'
            ));
            PREPARE stmt FROM @sql;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql="ALTER TABLE patient ADD COLUMN prediction VARCHAR(10);"
        ),
        migrations.RunSQL(
            """
            SET @sql = (SELECT IF(
                (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
                 WHERE table_name = 'patient' 
                 AND table_schema = DATABASE() 
                 AND column_name = 'prediction_probability') > 0,
                'ALTER TABLE patient DROP COLUMN prediction_probability',
                'SELECT 1'
            ));
            PREPARE stmt FROM @sql;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql="ALTER TABLE patient ADD COLUMN prediction_probability FLOAT;"
        ),
    ]
