# Generated by Django 4.2.7 on 2025-10-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lung_cancer', '0005_auto_20251029_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('호흡기내과', '호흡기내과'), ('외과', '외과')], max_length=20)),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('접수완료', '접수완료'), ('진료중', '진료중'), ('진료완료', '진료완료')], default='접수완료', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '진료기록',
                'verbose_name_plural': '진료기록 목록',
                'db_table': 'medical_record',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
    ]
