# Generated by Django 4.2.7 on 2025-10-29 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lung_cancer', '0006_medicalrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={'managed': False, 'ordering': ['-reception_start_time'], 'verbose_name': '진료기록', 'verbose_name_plural': '진료기록 목록'},
        ),
    ]
