# Generated by Django 4.2.7 on 2025-10-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lung_cancer', '0007_alter_medicalrecord_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecordNew',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_id', models.CharField(max_length=10, verbose_name='환자ID')),
                ('name', models.CharField(max_length=100, verbose_name='환자명')),
                ('department', models.CharField(choices=[('호흡기내과', '호흡기내과'), ('외과', '외과')], max_length=20, verbose_name='진료과')),
                ('status', models.CharField(choices=[('접수완료', '접수완료'), ('진료중', '진료중'), ('진료완료', '진료완료')], default='접수완료', max_length=20, verbose_name='진료상태')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='진료노트')),
                ('reception_start_time', models.DateTimeField(auto_now_add=True, verbose_name='접수시작시간')),
                ('treatment_end_time', models.DateTimeField(blank=True, null=True, verbose_name='진료끝난시간')),
                ('is_treatment_completed', models.BooleanField(default=False, verbose_name='진료완료여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '진료기록',
                'verbose_name_plural': '진료기록 목록',
                'db_table': 'medical_record_new',
                'managed': False,
                'ordering': ['-reception_start_time'],
            },
        ),
    ]
