# Generated by Django 4.2.7 on 2025-10-29 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lung_cancer', '0008_auto_20251030_0006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicalRecordNew',
        ),
    ]
