# Generated by Django 4.2.7 on 2025-11-03 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lung_cancer', '0009_delete_medicalrecordnew'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LungCancerPatient',
        ),
    ]
