# Generated by Django 4.2.7 on 2025-12-19 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lung_cancer", "0010_delete_lungcancerpatient"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientAppointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_id", models.CharField(max_length=10, verbose_name="환자ID")),
                (
                    "patient_name",
                    models.CharField(max_length=100, verbose_name="환자명"),
                ),
                ("appointment_date", models.DateField(verbose_name="예약일자")),
                ("appointment_time", models.TimeField(verbose_name="예약시간")),
                (
                    "appointment_type",
                    models.CharField(
                        choices=[
                            ("일반검진", "일반검진"),
                            ("정기검진", "정기검진"),
                            ("추가검사", "추가검사"),
                        ],
                        max_length=20,
                        verbose_name="검사유형",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("예약대기", "예약대기"),
                            ("예약확정", "예약확정"),
                            ("검사완료", "검사완료"),
                            ("예약취소", "예약취소"),
                        ],
                        default="예약대기",
                        max_length=20,
                        verbose_name="예약상태",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="특이사항"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="연락처")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "환자 예약",
                "verbose_name_plural": "환자 예약 목록",
                "db_table": "patient_appointments",
                "ordering": ["-appointment_date", "appointment_time"],
            },
        ),
    ]
