# Generated by Django 4.2.7 on 2025-11-13 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_appointment'),
        ('lung_cancer', '0011_add_doctor_foreign_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LungCancerPatient',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
            ],
            options={
                'ordering': ['-created_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('patients.patient',),
        ),
    ]
