# Generated by Django 4.2.7 on 2025-11-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=10, verbose_name='환자 ID')),
                ('image_type', models.CharField(choices=[('XRAY', 'X-ray'), ('CT', 'CT'), ('MRI', 'MRI'), ('ULTRASOUND', '초음파'), ('OTHER', '기타')], max_length=20, verbose_name='이미지 타입')),
                ('image_file', models.ImageField(upload_to='medical_images/', verbose_name='이미지 파일')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('taken_date', models.DateTimeField(verbose_name='촬영일시')),
                ('doctor_notes', models.TextField(blank=True, verbose_name='의사 소견')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
            options={
                'verbose_name': '의료 이미지',
                'verbose_name_plural': '의료 이미지들',
                'ordering': ['-taken_date'],
            },
        ),
    ]

