# Generated by Django 4.2.7 on 2025-11-27 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical_images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('BREAST_MRI', '유방 MRI'), ('LUNG_CT', '폐 CT'), ('XRAY', 'X-ray'), ('OTHER', '기타')], default='BREAST_MRI', max_length=20, verbose_name='분석 유형')),
                ('results', models.JSONField(default=dict, verbose_name='분석 결과 (JSON)')),
                ('confidence', models.FloatField(blank=True, null=True, verbose_name='신뢰도 (%)')),
                ('findings', models.TextField(blank=True, verbose_name='발견사항')),
                ('recommendations', models.TextField(blank=True, verbose_name='권장사항')),
                ('model_version', models.CharField(default='1.0.0', max_length=50, verbose_name='모델 버전')),
                ('analysis_date', models.DateTimeField(auto_now_add=True, verbose_name='분석일시')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='medical_images.medicalimage', verbose_name='의료 이미지')),
            ],
            options={
                'verbose_name': 'AI 분석 결과',
                'verbose_name_plural': 'AI 분석 결과들',
                'ordering': ['-analysis_date'],
            },
        ),
    ]
