# Generated by Django 4.2.7 on 2025-11-27 12:44

from django.db import migrations, models
import medical_images.models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_images', '0002_aianalysisresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalimage',
            name='image_file',
            field=models.ImageField(upload_to=medical_images.models.medical_image_upload_path, verbose_name='이미지 파일'),
        ),
    ]
