# Generated by Django 4.2.7 on 2025-12-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_images', '0003_alter_medicalimage_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aianalysisresult',
            name='analysis_type',
            field=models.CharField(choices=[('BREAST_MRI', '유방 MRI'), ('BREAST_MRI_SEGMENTATION', '유방 MRI 세그멘테이션'), ('BREAST_MRI_CLASSIFICATION', '유방 MRI 종양분석'), ('LUNG_CT', '폐 CT'), ('XRAY', 'X-ray'), ('OTHER', '기타')], default='BREAST_MRI', max_length=30, verbose_name='분석 유형'),
        ),
    ]
