# Generated by Django 4.2.7 on 2025-10-28 08:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exam_type', models.CharField(choices=[('MRI', 'MRI'), ('CT', 'CT'), ('X-RAY', 'X-RAY'), ('ULTRASOUND', '초음파'), ('BLOOD_TEST', '혈액검사'), ('URINE_TEST', '소변검사'), ('OTHER', '기타')], max_length=20, verbose_name='검사 유형')),
                ('exam_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='검사일시')),
                ('body_part', models.CharField(max_length=100, verbose_name='검사 부위')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('in_progress', '진행중'), ('completed', '완료'), ('cancelled', '취소')], default='pending', max_length=20, verbose_name='상태')),
                ('doctor_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='담당 의사')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='검사 메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '검사',
                'verbose_name_plural': '검사들',
                'ordering': ['-exam_date'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_number', models.CharField(max_length=50, unique=True, verbose_name='환자번호')),
                ('name', models.CharField(max_length=100, verbose_name='환자명')),
                ('birth_date', models.DateField(verbose_name='생년월일')),
                ('gender', models.CharField(choices=[('M', '남성'), ('F', '여성'), ('O', '기타')], max_length=10, verbose_name='성별')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='전화번호')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='이메일')),
                ('address', models.TextField(blank=True, null=True, verbose_name='주소')),
                ('emergency_contact', models.TextField(blank=True, null=True, verbose_name='응급연락처')),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True, verbose_name='혈액형')),
                ('allergies', models.TextField(blank=True, null=True, verbose_name='알레르기')),
                ('medical_history', models.TextField(blank=True, null=True, verbose_name='병력')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '환자',
                'verbose_name_plural': '환자들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_type', models.CharField(choices=[('MRI', 'MRI'), ('CT', 'CT'), ('X-RAY', 'X-RAY'), ('ULTRASOUND', '초음파'), ('PHOTO', '사진'), ('OTHER', '기타')], max_length=20, verbose_name='이미지 유형')),
                ('body_part', models.CharField(max_length=100, verbose_name='촬영 부위')),
                ('image', models.ImageField(upload_to='medical_images/', verbose_name='이미지 파일')),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True, verbose_name='원본 파일명')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='파일 크기')),
                ('description', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드일')),
                ('examination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='hospital.examination', verbose_name='검사')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_images', to='hospital.patient', verbose_name='환자')),
            ],
            options={
                'verbose_name': '의료 이미지',
                'verbose_name_plural': '의료 이미지들',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='examination',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='hospital.patient', verbose_name='환자'),
        ),
        migrations.CreateModel(
            name='AIAnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analysis_type', models.CharField(choices=[('YOLO', 'YOLO 객체 탐지'), ('CLASSIFICATION', '분류'), ('SEGMENTATION', '분할'), ('DETECTION', '탐지'), ('OTHER', '기타')], max_length=20, verbose_name='분석 유형')),
                ('results', models.JSONField(verbose_name='분석 결과')),
                ('confidence', models.PositiveIntegerField(blank=True, null=True, verbose_name='신뢰도')),
                ('findings', models.TextField(blank=True, null=True, verbose_name='발견사항')),
                ('recommendations', models.TextField(blank=True, null=True, verbose_name='권장사항')),
                ('model_version', models.CharField(blank=True, max_length=50, null=True, verbose_name='모델 버전')),
                ('analysis_date', models.DateTimeField(auto_now_add=True, verbose_name='분석일')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='hospital.medicalimage', verbose_name='이미지')),
            ],
            options={
                'verbose_name': 'AI 분석 결과',
                'verbose_name_plural': 'AI 분석 결과들',
                'ordering': ['-analysis_date'],
            },
        ),
    ]
