# Generated by Django 4.2.7 on 2026-01-24 13:46

from django.conf import settings
from django.db import migrations, models, connection
import django.db.models.deletion
import uuid


def check_table_exists(table_name):
    """테이블이 존재하는지 확인"""
    with connection.cursor() as cursor:
        db_name = connection.settings_dict['NAME']
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.tables 
            WHERE table_schema = %s 
            AND table_name = %s
        """, [db_name, table_name])
        return cursor.fetchone()[0] > 0


def create_labtestresult_if_not_exists(apps, schema_editor):
    """LabTestResult 테이블이 없으면 생성 (이미 존재하면 스킵)"""
    if not check_table_exists('ocs_labtestresult'):
        # 테이블이 없으면 Django 마이그레이션으로 생성
        LabTestResult = apps.get_model('ocs', 'LabTestResult')
        schema_editor.create_model(LabTestResult)


def reverse_create_labtestresult(apps, schema_editor):
    """LabTestResult 테이블 삭제"""
    if check_table_exists('ocs_labtestresult'):
        LabTestResult = apps.get_model('ocs', 'LabTestResult')
        schema_editor.delete_model(LabTestResult)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ocs', '0003_order_type_tissue_exam'),
    ]

    operations = [
        # LabTestResult 모델 정의 (테이블이 없을 때만 생성)
        migrations.CreateModel(
            name='LabTestResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_results', models.JSONField(default=dict, verbose_name='검사 결과 데이터')),
                ('ai_findings', models.TextField(blank=True, verbose_name='AI 소견')),
                ('ai_confidence_score', models.FloatField(blank=True, null=True, verbose_name='AI 신뢰도')),
                ('ai_report_image', models.TextField(blank=True, verbose_name='AI 임상 리포트 이미지 (base64)')),
                ('ai_prediction', models.CharField(blank=True, max_length=50, verbose_name='AI 예측 결과')),
                ('notes', models.TextField(blank=True, verbose_name='추가 메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='입력일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '검사 결과',
                'verbose_name_plural': '검사 결과들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(
            create_labtestresult_if_not_exists,
            reverse_create_labtestresult,
        ),
        migrations.CreateModel(
            name='PathologyAnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('class_id', models.IntegerField(verbose_name='클래스 ID')),
                ('class_name', models.CharField(max_length=50, verbose_name='클래스 이름')),
                ('confidence', models.FloatField(verbose_name='신뢰도')),
                ('probabilities', models.JSONField(default=dict, verbose_name='클래스별 확률')),
                ('filename', models.CharField(max_length=500, verbose_name='파일명')),
                ('image_url', models.TextField(blank=True, verbose_name='이미지 URL')),
                ('findings', models.TextField(blank=True, verbose_name='소견')),
                ('recommendations', models.TextField(blank=True, verbose_name='권고사항')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='분석일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '병리 분석 결과',
                'verbose_name_plural': '병리 분석 결과들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='ocs_notific_user_id_916063_idx',
            old_name='ocs_notific_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='ocs_notific_user_id_5f6483_idx',
            old_name='ocs_notific_user_cr_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='ocs_notific_notific_c3a3d9_idx',
            old_name='ocs_notific_type_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='ocs_order_patient_4124cc_idx',
            old_name='ocs_order_patient_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='ocs_order_doctor__cd300e_idx',
            old_name='ocs_order_doctor_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='ocs_order_target__efe302_idx',
            old_name='ocs_order_target_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='ocs_order_priorit_0fa20a_idx',
            old_name='ocs_order_priority_idx',
        ),
        migrations.AlterField(
            model_name='allergycheck',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='druginteractioncheck',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='imaginganalysisresult',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='pathologyanalysisresult',
            name='analyzed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pathology_analyses', to=settings.AUTH_USER_MODEL, verbose_name='분석자'),
        ),
        migrations.AddField(
            model_name='pathologyanalysisresult',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pathology_analysis', to='ocs.order', verbose_name='주문'),
        ),
        # LabTestResult의 input_by와 order 필드는 이미 위에서 CreateModel에 포함됨
    ]
